---
- name: Upload wg_setup systemd unit template
  copy:
    src: wg_setup@.service
    dest: /etc/systemd/system/
    mode: 0755

- name: Generate and upload systemd configurations for wg_setup
  template:
    src: wg_setup.conf.j2
    dest: "/etc/wireguard/wg_setup-{{ wg_interface_name }}"
  # vars:
  #   wg_interface_name: "{{ wg_interface_name }}"
  #   client_ip: "{{ client_ip }}"
  #   config_path: "{{ config_path }}"

- name: enable wg_setup@.services for wg0
  systemd:
    daemon-reload: yes
    daemon-reexec: yes
    state: restarted
    name: wg_setup@wg0.service
    enabled: yes