---
- hosts: dummies,zeroes
  become: yes
  gather_facts: no
  tasks:

  # - name: 
  #   debug:
  #     msg: "{{ default_user }}"

  - name: Remove the user 'pi'
    user:
      name: pi
      state: absent
      remove: yes

  - name: Remove home directory of user 'pi' 
    file:
      path: /home/pi
      state: absent