---
- name: Add user 'heads-tails'
  user:
    name: heads-tails
    password: $6$qy436SrOy8KG6B2M$xQfFz49dxKA1titii9CMB.HjEx43SaAaV/NsO/d.ovflX7yRWH7T0ODp8dDdzJR8QFYm.vyuoUSiNtURMv6Re.
    shell: /bin/bash
    create_home: yes
    append: yes
    state: present
    groups: sudo

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Set authorized key for MacBook to access 'heads-tails'
  authorized_key:
    user: heads-tails
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYS3HXGzz8v0ZBBiVhuObUlW+p6NRVcWlxfll/m+UbUp9h+TOSycKilJaUOmx/UmJ0kvb9pB5zwQjmFwYcBHDTUTeoau1YiJhlh2g3CkNXdw8oxpsIXvs3rXfHMv7V9BqtFkiSOG5IPNtdZ6m6tkocefwTWkowDCJEb1mqyEQIcgjxubjlqAjFtDVIVaR4RoWAEVBGRaCXbnMKDGiki1M/n2svm95mJiJ406nWbSE+cHhL97xkJbjh06kfvUhY3E1qOJhMfXY4lVRdGiZmAWA45JfxLrtCXhyBIK0jxyztcG8HKRKa8RZ4pvc8I0XHBMhNYXAO2hqpztgVJZzjoM/5 phillipstearns@MacBook"

- name: Set authorized key for mhl-00 to access 'heads-tails'
  authorized_key:
    user: heads-tails
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSHh+9j9fmjiAGb9ODO0Tq2NoqDqVtDBt32UgUlC8oKyjaL3AFdKjmpqoTICEx/PqXnXMvOLXjOMshNX5G6eSS7Py08qCoJyZlE8RY1PVACizWRRXtbdFyszV5SlIUjl+8bW7YuDE/7rKL65dlkn9DRTZPi42shey+cA3c2e2+0zyiNpoVo3q4BTKVblk/M6kpuwCDS+GBg+JC9KIHgp/puU/iL1QxvtrJp3W1jIvUAjX8dE3MQv9bNjLhdxXM/aMaXTj66tXEfV23dXReNARs63JTyM29aFefxlB5Hrr1mjWHnJX+aLvF0FgDVR0jLiuiH7TPasuLFIK7IBpVDOOP phillipstearns@milkandhoneylabs"

- name: Set authorized key for heads-tails-02
  authorized_key:
    user: heads-tails
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDtjZbW3WmzS8BknR/CcNUkC1Fl730wjV4DmV/ApMU/XDQubpRHDUdZ4+eZ2yiR+sw72164cJdt/9cDsZXAL8PT9tFJhAZD3zVGb2+kyz6CKSPxR0mmM+ZYh6us+qtKpnemi0FXbRnXDSPCGZd4oLbEeT613/uvdfA02s6iAESc0pUy16+g3aYEnS/Oyvm8d5xFb7CW5q6Amd/U5GSh3IloN40golhPajFIinj0uqZ0j1zynN815ZZALSwN6zN/1eDJ4rKVsD2b15UCKppV4VAUJSs7BJoz/kcp2emrCDX2SegkSg65snhocE0dS5OWGCbdHp0fZ+AsOJ9KVYSBqmAp heads-tails@heads-tails-02"

- name: Set authorized key for heads-tails-01
  authorized_key:
    user: heads-tails
    state: present
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDI7mJWFhnsGwUHpJ/m7At8++7BomWao8e+cbuTOiAGKmduo0yzASpFO/euIBtDg1+BsMmIq1fABxS4J9mx8oSYQ1/+4kfqecFkQV8dHrULn17TRwnSZb/w14PyUwxTI47BwEvypXxJr+H93dAhiZtHQQ+bqr3RRThw5tt1WwKcIA3xq+EEBZnxu+KpzYlPDnNl65vPaAWSUTz+ihKRhyw5rQanmvhKJ/MHGYsU08aXJWlgYicbUKioFL4NNn3W/riLRKuICsDD0yknKJlnZ69xMWtYCuT3fZ1mV0JKs6R8NHN1QRb0TcDUxLv38JhQ+m1vBvBR4RAWf47Vi6NjCGdp heads-tails@heads-tails-01"

- name: Change root password
  user:
    name: root
    password: $6$hSgxY5gWy9UwTxfw$KLG3r9dVuMKx.knPGSGuYs2EpZgGc8r0BIpwDjPSdcS7kSpfMLimx4hRCwmDR.9WV927SV5jgKBsOSN6eEckQ.

- name: Disable Password Authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present

- name: Disable Root Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present

- name: restart ssh
  service:
    name: sshd
    state: restarted